name: ai4pfas
channels:
- rdkit
- conda-forge
- pytorch
dependencies:
- pip
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- scipy
- scikit-learn
- pytorch
- autograd
- python=3.11
- pip:
  - gpflow
  - torch-geometric
  - tensorflow
  - tensorflow-probability
